version: '3'

services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "icommerce"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
